Repository ovh-ux/ovh-ui-angular, pull requests merged in 2018-10, with the labels that each got.

#274 fix(oui-field): fix getFirstError return
  packages/oui-field/src/field.controller.js
Labels: bug

#279 fix(oui-chips): fix item removal
  packages/oui-chips/src/chips.controller.js
  packages/oui-chips/src/chips.html
  yarn.lock
Labels: bug

#280 fix(oui-select-picker): fix main classname on component
  packages/oui-select-picker/src/select-picker.controller.js
  packages/oui-select-picker/src/select-picker.html
Labels: bug

#282 fix(oui-select-picker): add selection on init if model is set
  packages/oui-select-picker/src/select-picker.controller.js
Labels: bug

#283 style: fix json output
  packages/oui-criteria-adder/README.md
  packages/oui-stepper/README.md
Labels: bug

#291 feat(oui-select): allow items to be disabled
  packages/oui-select/README.md
  packages/oui-select/src/index.spec.js
  packages/oui-select/src/select.directive.js
  packages/oui-select/src/select.html
  packages/oui-select/src/templates/choices.html
Labels: enhancement

#296 feat(oui-datagrid): permit to access row index
  packages/oui-datagrid/README.md
  packages/oui-datagrid/src/cell/cell.controller.js
  packages/oui-datagrid/src/index.spec.js
Labels: enhancement

#297 fix(oui-select-picker): fix click propagation on parent label
  packages/oui-select-picker/src/select-picker.controller.js
Labels: bug

#301 feat(oui-popover): add ng-template and title attribute support
  packages/oui-popover/README.md
  packages/oui-popover/src/content/popover-content.directive.js
  packages/oui-popover/src/content/popover-content.html
  packages/oui-popover/src/index.js
  packages/oui-popover/src/index.spec.js
  packages/oui-popover/src/popover-content.html
  packages/oui-popover/src/popover-trigger.directive.js
  packages/oui-popover/src/popover.component.js
  packages/oui-popover/src/popover.controller.js
  packages/oui-popover/src/popover.directive.js
  packages/oui-popover/src/popover.html
  packages/oui-popover/src/trigger/popover-trigger.controller.js
  packages/oui-popover/src/trigger/popover-trigger.directive.js
  packages/oui-tooltip/src/tooltip.controller.js
Labels: enhancement

#302 fix(oui-calendar): fix boolean parameters
  packages/oui-calendar/README.md
  packages/oui-calendar/src/calendar.controller.js
Labels: bug, enhancement

#303 fix(oui-select): prevent required validation to trigger on select
  packages/oui-select/src/select.html
Labels: bug
