Repository ovh-ux/ovh-ui-angular, pull requests merged in 2018-04, with the labels that each got.

#100 feat(select-picker): create component
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-select-picker/README.md
  packages/oui-select-picker/src/index.js
  packages/oui-select-picker/src/index.spec.js
  packages/oui-select-picker/src/select-picker.component.js
  packages/oui-select-picker/src/select-picker.controller.js
  packages/oui-select-picker/src/select-picker.html
  packages/oui-select/src/select.controller.js
  packages/oui-select/src/select.directive.js
Labels: feature

#152 feat(oui-popover): add new Popover component
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-popover/README.md
  packages/oui-popover/src/index.js
  packages/oui-popover/src/index.spec.js
  packages/oui-popover/src/popover-content.directive.js
  packages/oui-popover/src/popover-content.html
  packages/oui-popover/src/popover-trigger.directive.js
  packages/oui-popover/src/popover.component.js
  packages/oui-popover/src/popover.controller.js
  packages/oui-popover/src/popover.html
Labels: feature, quality check ok

#150 fix(oui-tooltip): fix tooltip postLink with timeout
  packages/oui-tooltip/README.md
  packages/oui-tooltip/src/index.spec.js
  packages/oui-tooltip/src/tooltip.controller.js
Labels: bug

#155 fix(oui-radio): boolean parameter missing on thumbnail attr
  packages/oui-radio/README.md
  packages/oui-radio/src/index.spec.js
  packages/oui-radio/src/radio.controller.js
Labels: bug

#160 feat(oui-radio): add required attribute
  packages/oui-radio/README.md
  packages/oui-radio/src/index.spec.js
  packages/oui-radio/src/radio.component.js
  packages/oui-radio/src/radio.controller.js
  packages/oui-radio/src/radio.html
Labels: enhancement

#165 fix(oui-datagrid): fix util/hasProperty exception
  packages/oui-datagrid/src/util.js
Labels: bug, ok for merge

#168 feat(oui-field): add the label popover option
  packages/oui-field/README.md
  packages/oui-field/src/field.component.js
  packages/oui-field/src/field.controller.js
  packages/oui-field/src/field.html
  packages/oui-field/src/index.spec.js
Labels: feature

#169 fix(oui-select-picker): fix value selection with one option only
  packages/oui-select-picker/src/select-picker.controller.js
  packages/oui-select-picker/src/select-picker.html
Labels: bug

#166 fix(oui-select): fix dropdown min-width
  packages/oui-select/src/templates/select.html
  packages/oui-select/src/ui-select.js
Labels: enhancement

#170 fix(oui-radio): fix radio toggle / thumbnail conflict
  packages/oui-radio/src/index.spec.js
  packages/oui-radio/src/radio.controller.js
  packages/oui-radio/src/radio.html
Labels: bug

#172 chore(oui-stepper): remove linear and add cancel button
  packages/oui-stepper/README.md
  packages/oui-stepper/src/index.spec.js
  packages/oui-stepper/src/step-form/step-form.component.js
  packages/oui-stepper/src/step-form/step-form.controller.js
  packages/oui-stepper/src/step-form/step-form.html
  packages/oui-stepper/src/stepper.component.js
  packages/oui-stepper/src/stepper.controller.js
  packages/oui-stepper/src/stepper.provider.js
Labels: feature, ok for merge

#151 style(oui-navbar): navbar header must be displayed on full browser
  packages/oui-navbar/src/navbar.html
Labels: enhancement, ok for merge

#176 fix(oui-select-picker): fix matched value display
  packages/oui-select-picker/src/select-picker.controller.js
  packages/oui-select-picker/src/select-picker.html
Labels: bug
