Repository ovh-ux/ovh-ui-angular, pull requests merged in 2018-07, with the labels that each got.

#226 fix(oui-dropdown): fix dropdown placement
  package.json
  packages/oui-dropdown/src/dropdown.controller.js
  yarn.lock
Labels: bug

#192 feat(oui-progress): progress component implementation
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-progress/README.md
  packages/oui-progress/src/bar/progress-bar.component.js
  packages/oui-progress/src/bar/progress-bar.controller.js
  packages/oui-progress/src/bar/progress-bar.html
  packages/oui-progress/src/index.js
  packages/oui-progress/src/index.spec.js
  packages/oui-progress/src/progress.component.js
  packages/oui-progress/src/progress.controller.js
  packages/oui-progress/src/threshold/progress-threshold.component.js
  packages/oui-progress/src/threshold/progress-threshold.controller.js
Labels: cui migration, feature, quality check

#191 feat(oui-switch): add new oui-switch component
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-field/README.md
  packages/oui-switch/README.md
  packages/oui-switch/src/index.js
  packages/oui-switch/src/index.spec.js
  packages/oui-switch/src/switch.component.js
  packages/oui-switch/src/switch.controller.js
  packages/oui-switch/src/switch.html
Labels: feature, quality check ok

#231 hotfix(oui-criteria-adder)
  packages/oui-criteria-adder/src/criteria-adder.controller.js
  packages/oui-criteria-adder/src/criteria-adder.html
Labels: bug

#232 fix(oui-action-menu): allow to disable action menu dynamically
  packages/oui-action-menu/src/action-menu.component.js
Labels: bug

#229 fix(oui-popover): update style to specs
  packages/oui-field/src/field.html
  packages/oui-popover/README.md
  packages/oui-tile/src/definition/tile-definition.html
  packages/oui-tile/src/index.spec.js
Labels: bug

#234 feat(oui-tile): add external link handle
  packages/oui-tile/README.md
  packages/oui-tile/src/button/tile-button.component.js
  packages/oui-tile/src/button/tile-button.controller.js
  packages/oui-tile/src/button/tile-button.html
  packages/oui-tile/src/index.spec.js
Labels: enhancement

#236 chore: optimize for webpack
  packages/oui-action-menu/src/index.js
  packages/oui-angular/src/index.js
  packages/oui-back-button/src/index.js
  packages/oui-button/src/index.js
  packages/oui-calendar/src/calendar.provider.js
  packages/oui-calendar/src/index.js
  packages/oui-checkbox/src/index.js
  packages/oui-chips/src/index.js
  packages/oui-chips/src/index.spec.js
  packages/oui-clipboard/src/clipboard.provider.js
  packages/oui-clipboard/src/index.js
  packages/oui-collapsible/src/index.js
  packages/oui-criteria-adder/src/criteria-adder.controller.js
  packages/oui-criteria-adder/src/index.js
  packages/oui-criteria-adder/src/index.spec.js
  packages/oui-criteria-container/src/criteria-container.controller.js
  packages/oui-criteria-container/src/index.js
  packages/oui-datagrid/src/datagrid.controller.js
  packages/oui-datagrid/src/filter/comparator-resolver.js
  packages/oui-datagrid/src/filter/date.js
  packages/oui-datagrid/src/filter/filter.js
  packages/oui-datagrid/src/index.js
  packages/oui-field/src/index.js
  packages/oui-field/src/index.spec.js
  packages/oui-form-actions/src/index.js
  packages/oui-guide-menu/src/index.js
  packages/oui-header-tabs/src/index.js
  packages/oui-message/src/index.js
  packages/oui-message/src/index.spec.js
  packages/oui-modal/src/index.js
  packages/oui-navbar/src/index.js
  packages/oui-numeric/src/index.js
  packages/oui-numeric/src/numeric.controller.js
  packages/oui-page-header/src/index.js
  packages/oui-pagination/src/index.js
  packages/oui-popover/src/index.js
  packages/oui-progress/src/index.js
  packages/oui-radio-group/src/index.js
  packages/oui-radio-toggle-group/src/index.js
  packages/oui-radio/src/index.js
  packages/oui-search/src/index.js
  packages/oui-search/src/search.controller.js
  packages/oui-select-picker/src/index.js
  packages/oui-select-picker/src/select-picker.controller.js
  packages/oui-select/src/index.js
  packages/oui-select/src/index.spec.js
  packages/oui-skeleton/src/index.js
  packages/oui-slideshow/src/index.js
  packages/oui-spinner/src/index.js
  packages/oui-stepper/src/index.js
  packages/oui-stepper/src/stepper.provider.js
  packages/oui-switch/src/index.js
  packages/oui-textarea/src/index.js
  packages/oui-tile/src/index.js
  packages/oui-tooltip/src/index.js
Labels: enhancement

#235 feat(oui-navbar): add new components
  packages/oui-header-tabs/README.md
  packages/oui-navbar/README.md
  packages/oui-navbar/src/brand/navbar-brand.component.js
  packages/oui-navbar/src/brand/navbar-brand.html
  packages/oui-navbar/src/dropdown/menu/navbar-dropdown-menu.component.js
  packages/oui-navbar/src/dropdown/navbar-dropdown.component.js
  packages/oui-navbar/src/dropdown/navbar-dropdown.controller.js
  packages/oui-navbar/src/dropdown/navbar-dropdown.html
  packages/oui-navbar/src/group/navbar-group.controller.js
  packages/oui-navbar/src/group/navbar-group.directive.js
  packages/oui-navbar/src/group/navbar-group.service.js
  packages/oui-navbar/src/index.js
  packages/oui-navbar/src/index.spec.js
  packages/oui-navbar/src/keyboard-keys.constant.js
  packages/oui-navbar/src/link/navbar-link.component.js
  packages/oui-navbar/src/link/navbar-link.controller.js
  packages/oui-navbar/src/link/navbar-link.html
  packages/oui-navbar/src/menu/navbar-menu.component.js
  packages/oui-navbar/src/menu/navbar-menu.controller.js
  packages/oui-navbar/src/menu/navbar-menu.html
  packages/oui-navbar/src/navbar.component.js
  packages/oui-navbar/src/navbar.controller.js
  packages/oui-navbar/src/navbar.html
  packages/oui-navbar/src/navbar.provider.js
  packages/oui-navbar/src/navbar.service.js
  packages/oui-navbar/src/notification/navbar-notification.component.js
  packages/oui-navbar/src/notification/navbar-notification.controller.js
  packages/oui-navbar/src/notification/navbar-notification.html
  packages/oui-navbar/src/toggler/navbar-toggler.component.js
  packages/oui-navbar/src/toggler/navbar-toggler.controller.js
  packages/oui-navbar/src/toggler/navbar-toggler.html
Labels: feature

#237 feat(oui-tile): add disabled on oui-tile-button
  packages/oui-tile/README.md
  packages/oui-tile/src/button/tile-button.component.js
  packages/oui-tile/src/button/tile-button.controller.js
  packages/oui-tile/src/button/tile-button.html
  packages/oui-tile/src/index.spec.js
Labels: feature
