Repository ovh-ux/ovh-ui-angular, pull requests merged in 2018-06, with the labels that each got.

#173 feat(oui-collapsible): collapsible component addition
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-collapsible/README.md
  packages/oui-collapsible/src/collapsible.component.js
  packages/oui-collapsible/src/collapsible.controller.js
  packages/oui-collapsible/src/collapsible.html
  packages/oui-collapsible/src/index.js
  packages/oui-collapsible/src/index.spec.js
Labels: cui migration, feature, ok for merge, quality check ok

#185 feat: oui skeleton
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-skeleton/README.md
  packages/oui-skeleton/src/index.js
  packages/oui-skeleton/src/index.spec.js
  packages/oui-skeleton/src/skeleton.component.js
  packages/oui-skeleton/src/skeleton.controller.js
  packages/oui-skeleton/src/skeleton.html
Labels: cui migration, feature, ok for merge, quality check ok

#195 fix(oui-action-menu): disable one-time binding for the text attribute
  packages/oui-action-menu/README.md
  packages/oui-action-menu/src/action-menu-item-button.html
Labels: bug

#184 feat(oui-slideshow): add new slideshow component
  dist/oui-angular.min.js
  dist/oui-angular.min.js.map
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-popover/src/popover-content.html
  packages/oui-slideshow/README.md
  packages/oui-slideshow/src/index.js
  packages/oui-slideshow/src/index.spec.js
  packages/oui-slideshow/src/slideshow-panel.component.js
  packages/oui-slideshow/src/slideshow-panel.controller.js
  packages/oui-slideshow/src/slideshow-panel.html
  packages/oui-slideshow/src/slideshow.component.js
  packages/oui-slideshow/src/slideshow.controller.js
  packages/oui-slideshow/src/slideshow.html
Labels: feature, quality check ok

#202 fix(oui-slideshow): updade slideshow module naming
  dist/oui-angular.min.js
  dist/oui-angular.min.js.map
  packages/oui-angular/src/index.js
  packages/oui-slideshow/src/index.js
  packages/oui-slideshow/src/index.spec.js
Labels: enhancement

#196 feat(oui-datagrid): add datagrid customization
  packages/oui-datagrid/README.md
  packages/oui-datagrid/src/cell/cell.controller.js
  packages/oui-datagrid/src/datagrid-column-builder.service.js
  packages/oui-datagrid/src/datagrid.controller.js
  packages/oui-datagrid/src/datagrid.directive.js
  packages/oui-datagrid/src/datagrid.html
  packages/oui-datagrid/src/index.js
  packages/oui-datagrid/src/index.spec.js
  packages/oui-datagrid/src/parameters/datagrid-parameters.component.js
  packages/oui-datagrid/src/parameters/datagrid-parameters.controller.js
  packages/oui-datagrid/src/parameters/datagrid-parameters.html
  packages/oui-datagrid/src/parameters/datagrid-parameters.spec.js
Labels: feature

#203 fix(oui-stepper): remove one time-binding on description
  packages/oui-stepper/src/step-form/step-form.html
Labels: enhancement

#197 feat(oui-field): add custom message support
  packages/oui-field/src/field.controller.js
  packages/oui-field/src/field.html
Labels: feature

#204 feat(oui-page-header): create page-header component
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-page-header/README.md
  packages/oui-page-header/src/index.js
  packages/oui-page-header/src/index.spec.js
  packages/oui-page-header/src/page-header.component.js
  packages/oui-page-header/src/page-header.controller.js
  packages/oui-page-header/src/page-header.html
Labels: feature, ok for merge, quality check ok

#200 feat(oui-tile): create component
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-tile/README.md
  packages/oui-tile/src/button/tile-button.component.js
  packages/oui-tile/src/button/tile-button.controller.js
  packages/oui-tile/src/button/tile-button.html
  packages/oui-tile/src/definition/tile-definition.component.js
  packages/oui-tile/src/definition/tile-definition.controller.js
  packages/oui-tile/src/definition/tile-definition.html
  packages/oui-tile/src/index.js
  packages/oui-tile/src/index.spec.js
  packages/oui-tile/src/tile.component.js
  packages/oui-tile/src/tile.controller.js
  packages/oui-tile/src/tile.html
Labels: feature, quality check ok

#207 Feat/guide
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-guide-menu/README.md
  packages/oui-guide-menu/src/guide-menu.component.js
  packages/oui-guide-menu/src/guide-menu.html
  packages/oui-guide-menu/src/index.js
  packages/oui-guide-menu/src/index.spec.js
  packages/oui-page-header/README.md
  packages/oui-page-header/src/page-header.component.js
Labels: feature, quality check ok

#209 feat(oui-header-tabs): add header-tabs component
  dist/oui-angular.min.js
  dist/oui-angular.min.js.map
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-dropdown/src/trigger/dropdown-trigger.controller.js
  packages/oui-header-tabs/README.md
  packages/oui-header-tabs/src/header-tabs-dropdown.component.js
  packages/oui-header-tabs/src/header-tabs-dropdown.html
  packages/oui-header-tabs/src/header-tabs-item.component.js
  packages/oui-header-tabs/src/header-tabs-item.controller.js
  packages/oui-header-tabs/src/header-tabs-item.html
  packages/oui-header-tabs/src/header-tabs.component.js
  packages/oui-header-tabs/src/header-tabs.controller.js
  packages/oui-header-tabs/src/header-tabs.html
  packages/oui-header-tabs/src/index.js
  packages/oui-header-tabs/src/index.spec.js
Labels: feature, quality check ok

#212 fix(oui-header-tabs): add active class when dropdown has an active item
  packages/oui-header-tabs/src/header-tabs-dropdown.component.js
Labels: bug

#218 fix(oui-datagrid): fix type options with dynamic columns
  packages/oui-datagrid/README.md
  packages/oui-datagrid/src/datagrid-column-builder.service.js
Labels: bug, ok for merge

#220 docs(oui-page-header): add missing header-tabs example
  packages/oui-page-header/README.md
Labels: enhancement

#219 fix(oui-tile): fix loading state
  packages/oui-tile/README.md
  packages/oui-tile/src/tile.html
Labels: bug

#221 fix(oui-tile): fix normalize for height sizing
  packages/oui-tile/src/tile.controller.js
  packages/oui-tile/src/tile.html
Labels: bug
