Repository ovh-ux/ovh-ui-angular, pull requests merged in 2018-05, with the labels that each got.

#175 feat(oui-modal): add type attribute to handle icon modal
  packages/oui-modal/README.md
  packages/oui-modal/src/index.spec.js
  packages/oui-modal/src/modal.component.js
  packages/oui-modal/src/modal.html
Labels: feature, ok for merge

#182 fix(oui-modal): allow 2 way binding on some attributes
  dist/oui-angular.min.js
  dist/oui-angular.min.js.map
  packages/oui-modal/src/modal.html
Labels: enhancement, ok for merge

#183 style(oui-navbar): add brand title
  packages/oui-navbar/README.md
  packages/oui-navbar/src/navbar.html
Labels: enhancement, ok for merge

#159 feat(oui-navbar): replace template by new notifications
  packages/oui-navbar/src/group/navbar-group.controller.js
  packages/oui-navbar/src/index.js
  packages/oui-navbar/src/index.spec.data.json
  packages/oui-navbar/src/menu/navbar-menu.controller.js
  packages/oui-navbar/src/navbar.controller.js
  packages/oui-navbar/src/navbar.html
  packages/oui-navbar/src/navbar.provider.js
  packages/oui-tooltip/src/tooltip.directive.js
  packages/oui-tooltip/src/tooltip.html
Labels: enhancement, ok for merge

#188 fix(oui-datagrid): wait row promise before displaying cell template
  packages/oui-datagrid/src/cell/cell.controller.js
Labels: bug
