Repository ovh-ux/ovh-ui-angular, pull requests merged in 2018-11, with the labels that each got.

#304 feat(oui-inline-adder): add inline-adder component
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-inline-adder/README.md
  packages/oui-inline-adder/src/field/inline-adder-field.component.js
  packages/oui-inline-adder/src/field/inline-adder-field.controller.js
  packages/oui-inline-adder/src/index.js
  packages/oui-inline-adder/src/index.spec.js
  packages/oui-inline-adder/src/inline-adder.component.js
  packages/oui-inline-adder/src/inline-adder.controller.js
  packages/oui-inline-adder/src/inline-adder.html
  packages/oui-inline-adder/src/inline-adder.provider.js
  packages/oui-inline-adder/src/row/inline-adder-row.component.js
Labels: feature

#305 feat(oui-navbar): allow actions on navbar menu links
  packages/oui-navbar/README.md
  packages/oui-navbar/src/index.spec.js
  packages/oui-navbar/src/link/navbar-link.component.js
  packages/oui-navbar/src/link/navbar-link.html
  packages/oui-navbar/src/menu/navbar-menu.html
  packages/oui-navbar/src/navbar.html
Labels: enhancement

#306 feat(oui-dropdown): allow click on link items
  packages/oui-dropdown/src/index.spec.js
  packages/oui-dropdown/src/item/dropdown-item.html
Labels: enhancement

#308 feat(oui-navbar): allow to animate icon on aside links
  packages/oui-navbar/README.md
  packages/oui-navbar/src/dropdown/navbar-dropdown.component.js
  packages/oui-navbar/src/dropdown/navbar-dropdown.html
  packages/oui-navbar/src/index.spec.data.json
  packages/oui-navbar/src/index.spec.js
  packages/oui-navbar/src/navbar.html
Labels: enhancement

#307 feat(oui-modal): allow disabling oui-modal buttons
  packages/oui-modal/README.md
  packages/oui-modal/src/index.spec.js
  packages/oui-modal/src/modal.component.js
  packages/oui-modal/src/modal.controller.js
  packages/oui-modal/src/modal.html
Labels: feature

#311 feat(oui-dual-list): add dual-list component
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-dual-list/README.md
  packages/oui-dual-list/package.json
  packages/oui-dual-list/src/dual-list.component.js
  packages/oui-dual-list/src/dual-list.controller.js
  packages/oui-dual-list/src/dual-list.provider.js
  packages/oui-dual-list/src/index.js
  packages/oui-dual-list/src/index.spec.data.json
  packages/oui-dual-list/src/index.spec.js
  packages/oui-dual-list/src/source/dual-list-source.component.js
  packages/oui-dual-list/src/source/dual-list-source.controller.js
  packages/oui-dual-list/src/source/dual-list-source.html
  packages/oui-dual-list/src/target/dual-list-target.component.js
  packages/oui-dual-list/src/target/dual-list-target.controller.js
  packages/oui-dual-list/src/target/dual-list-target.html
  packages/oui-inline-adder/package.json
  packages/oui-inline-adder/src/inline-adder.html
  packages/oui-inline-adder/src/inline-adder.provider.js
  packages/oui-navbar/src/navbar.provider.js
  packages/oui-pagination/src/pagination.html
  packages/oui-search/src/search.html
Labels: feature

#312 fix(oui-select-picker): fix transclude with component instead of span
  packages/oui-select-picker/README.md
  packages/oui-select-picker/src/index.js
  packages/oui-select-picker/src/section/select-picker-section.component.js
  packages/oui-select-picker/src/select-picker.component.js
  packages/oui-select-picker/src/select-picker.controller.js
  packages/oui-select-picker/src/select-picker.html
Labels: enhancement

#315 feat(oui-autocomplete): add autocomplete directive
  package.json
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-autocomplete/README.md
  packages/oui-autocomplete/package.json
  packages/oui-autocomplete/src/autocomplete.controller.js
  packages/oui-autocomplete/src/autocomplete.directive.js
  packages/oui-autocomplete/src/autocomplete.html
  packages/oui-autocomplete/src/autocomplete.provider.js
  packages/oui-autocomplete/src/filter/autocomplete-highlight.filter.js
  packages/oui-autocomplete/src/index.js
  packages/oui-autocomplete/src/index.spec.data.json
  packages/oui-autocomplete/src/index.spec.js
  packages/oui-search/README.md
  packages/oui-search/src/search.component.js
  packages/oui-search/src/search.html
  yarn.lock
Labels: feature, ok for merge

#319 feat(oui-tabs): add tabs component
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-tabs/README.md
  packages/oui-tabs/package.json
  packages/oui-tabs/src/index.js
  packages/oui-tabs/src/index.spec.js
  packages/oui-tabs/src/item/tabs-item.component.js
  packages/oui-tabs/src/item/tabs-item.controller.js
  packages/oui-tabs/src/item/tabs-item.html
  packages/oui-tabs/src/tabs.component.js
  packages/oui-tabs/src/tabs.controller.js
  packages/oui-tabs/src/tabs.html
Labels: feature, quality check ok
