Repository ovh-ux/ovh-ui-angular, pull requests merged in 2018-09, with the labels that each got.

#254 feat(oui-datagrid): add a way to customize empty placeholder
  packages/oui-datagrid/README.md
  packages/oui-datagrid/src/datagrid.directive.js
  packages/oui-datagrid/src/datagrid.html
Labels: feature

#253 feat(oui-calendar): add enableTime option
  packages/oui-calendar/README.md
  packages/oui-calendar/src/calendar.component.js
  packages/oui-calendar/src/calendar.controller.js
Labels: enhancement, feature

#257 refactor(oui-radio): update project structure
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-radio-group/README.md
  packages/oui-radio-group/src/index.js
  packages/oui-radio-group/src/index.spec.js
  packages/oui-radio-toggle-group/README.md
  packages/oui-radio-toggle-group/src/index.js
  packages/oui-radio-toggle-group/src/index.spec.js
  packages/oui-radio/README.md
  packages/oui-radio/src/group/radio-group.component.js
  packages/oui-radio/src/group/radio-group.controller.js
  packages/oui-radio/src/index.js
  packages/oui-radio/src/index.spec.js
  packages/oui-radio/src/toggle-group/radio-toggle-group.component.js
Labels: enhancement

#259 feat(oui-message): add dismissable attribute
  packages/oui-message/README.md
  packages/oui-message/src/message.component.js
  packages/oui-message/src/message.controller.js
  packages/oui-message/src/message.html
Labels: feature

#260 feat(oui-navbar): add onclick and manual control on toggler
  package.json
  packages/oui-navbar/README.md
  packages/oui-navbar/src/index.spec.js
  packages/oui-navbar/src/toggler/navbar-toggler.component.js
  packages/oui-navbar/src/toggler/navbar-toggler.controller.js
  packages/oui-navbar/src/toggler/navbar-toggler.html
  yarn.lock
Labels: feature

#269 feat(oui-select-picker): add default light templates
  packages/oui-select-picker/src/select-picker.component.js
  packages/oui-select-picker/src/select-picker.controller.js
Labels: enhancement

#273 Feat/select picker/default light templates
  packages/oui-select-picker/README.md
  packages/oui-select-picker/src/select-picker.html
Labels: enhancement
