Repository ovh-ux/ovh-ui-angular, pull requests merged in 2018-03, with the labels that each got.

#104 Feat(form-actions) : create component
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-form-actions/README.md
  packages/oui-form-actions/src/form-actions.component.js
  packages/oui-form-actions/src/form-actions.controller.js
  packages/oui-form-actions/src/form-actions.html
  packages/oui-form-actions/src/form-actions.provider.js
  packages/oui-form-actions/src/index.js
  packages/oui-form-actions/src/index.spec.js
Labels: feature, quality check ok

#105 feat(oui-search): add oui-search component
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-search/README.md
  packages/oui-search/src/index.js
  packages/oui-search/src/index.spec.js
  packages/oui-search/src/search.component.js
  packages/oui-search/src/search.controller.js
  packages/oui-search/src/search.html
Labels: feature, ok for merge

#108 chore: commitlint, commitizen and conventional-changelog integration
  .scriptsrc
  CHANGELOG.md
  CONTRIBUTING.md
  commitlint.config.js
  package.json
  yarn.lock
Labels: enhancement

#113 docs(oui-field): change helper-text attribute to help-text
  packages/oui-field/README.md
Labels: bug

#110 fix(select): make match optional (handle string list)
  packages/oui-select/README.md
  packages/oui-select/src/index.spec.js
  packages/oui-select/src/select.directive.js
Labels: enhancement

#109 feat(field): add custom error message and ng-pattern support
  packages/oui-field/README.md
  packages/oui-field/src/field.component.js
  packages/oui-field/src/field.controller.js
  packages/oui-field/src/field.html
  packages/oui-field/src/field.provider.js
  packages/oui-field/src/index.spec.js
Labels: enhancement

#123 feat(modal): add overlay and spinner to modal attribute while loading
  packages/oui-modal/README.md
  packages/oui-modal/src/index.spec.js
  packages/oui-modal/src/modal.component.js
  packages/oui-modal/src/modal.controller.js
  packages/oui-modal/src/modal.html
Labels: feature

#142 chore(oui-calendar): disable flatpickr mobile mode
  package.json
  packages/oui-calendar/README.md
  packages/oui-calendar/src/calendar.provider.js
Labels: bug
