Repository ovh-ux/ovh-ui-angular, pull requests merged in 2018-02, with the labels that each got.

#87 style(navbar): update template for internal menus
  packages/oui-navbar/src/group/navbar-group.service.js
  packages/oui-navbar/src/index.spec.data.json
  packages/oui-navbar/src/menu/navbar-menu.controller.js
  packages/oui-navbar/src/menu/navbar-menu.html
  packages/oui-navbar/src/navbar.controller.js
  packages/oui-navbar/src/navbar.html
Labels: enhancement, quality check ok

#92 feat(navbar): add a toggler-links attribute
  packages/oui-navbar/README.md
  packages/oui-navbar/src/index.spec.js
  packages/oui-navbar/src/navbar.component.js
  packages/oui-navbar/src/navbar.controller.js
  packages/oui-navbar/src/navbar.html
Labels: enhancement, quality check ok

#90 fix(datagrid): prevent datagrid to render empty cell when template is only white spaces
  packages/oui-datagrid/src/datagrid-column-builder.service.js
  packages/oui-datagrid/src/index.spec.js
Labels: bug, quality check ok

#85 feat(back-button): Add title attribute
  packages/oui-back-button/README.md
  packages/oui-back-button/src/back-button.component.js
  packages/oui-back-button/src/back-button.controller.js
  packages/oui-back-button/src/back-button.html
  packages/oui-back-button/src/index.spec.js
Labels: enhancement, quality check ok

#86 feat(select): add oui-select wrapper for ui-select
  build/karma.conf.js
  packages/oui-angular/src/index.js
  packages/oui-angular/src/index.spec.js
  packages/oui-select/README.md
  packages/oui-select/src/index.js
  packages/oui-select/src/index.spec.data.json
  packages/oui-select/src/index.spec.js
  packages/oui-select/src/select.controller.js
  packages/oui-select/src/select.directive.js
  packages/oui-select/src/select.html
  packages/oui-select/src/templates/choices.html
  packages/oui-select/src/templates/match.html
  packages/oui-select/src/templates/select.html
  packages/oui-select/src/ui-select.js
Labels: feature, ok for merge, quality check ok

#103 style(navbar): hide empty sublinks
  packages/oui-navbar/src/index.spec.data.json
  packages/oui-navbar/src/menu/navbar-menu.html
Labels: enhancement, quality check ok
