Repository ovh-ux/ovh-ui-angular, pull requests merged in 2019-01, with the labels that each got.

#338 fix(oui-select): nested property support for match api
  packages/oui-select/src/select.controller.js
  packages/oui-select/src/templates/match.html
Labels: bug, quality check

#342 fix(oui-slideshow): fix onDismiss callback
  packages/oui-slideshow/src/slideshow.controller.js
Labels: bug

#345 refactor(oui-criteria): refactor oui-criteria-container to oui-criteria
  packages/common/component-utils.js
  packages/oui-angular/package.json
  packages/oui-angular/src/index.js
  packages/oui-chips/src/chips.component.js
  packages/oui-chips/src/chips.controller.js
  packages/oui-chips/src/index.spec.js
  packages/oui-criteria-adder/src/index.js
  packages/oui-criteria-container/src/criteria-container.component.js
  packages/oui-criteria-container/src/criteria-container.controller.js
  packages/oui-criteria-container/src/index.js
  packages/oui-criteria-container/src/index.spec.js
  packages/oui-criteria-container/tests/index.js
  packages/oui-criteria/README.md
  packages/oui-criteria/package.json
  packages/oui-criteria/src/adder/criteria-adder.component.js
  packages/oui-criteria/src/adder/criteria-adder.controller.js
  packages/oui-criteria/src/adder/criteria-adder.html
  packages/oui-criteria/src/adder/criteria-adder.provider.js
  packages/oui-criteria/src/adder/criteria-adder.spec.data.json
  packages/oui-criteria/src/adder/criteria-adder.spec.js
  packages/oui-criteria/src/criteria.component.js
  packages/oui-criteria/src/criteria.controller.js
  packages/oui-criteria/src/criteria.html
  packages/oui-criteria/src/index.js
  packages/oui-criteria/src/index.spec.js
  packages/oui-criteria/tests/index.js
  packages/oui-datagrid/package.json
  packages/oui-datagrid/src/datagrid.controller.js
  packages/oui-datagrid/src/datagrid.html
  packages/oui-datagrid/src/index.js
  packages/oui-datagrid/src/index.spec.js
  packages/oui-search/README.md
  packages/oui-search/src/index.spec.js
  packages/oui-search/src/search.component.js
  packages/oui-search/src/search.controller.js
  packages/oui-search/src/search.html
Labels: enhancement

#350 Update select-picker.controller.js
  packages/oui-select-picker/src/select-picker.controller.js
Labels: ok for merge

#349 fix(oui-dropdown): fix dropdown menu positioning
  packages/oui-dropdown/src/dropdown.controller.js
Labels: bug, ok for merge

#348 feat(oui-datagrid): add skeletons when loading data
  packages/oui-datagrid/src/datagrid.html
  packages/oui-datagrid/src/index.spec.js
Labels: enhancement, quality check ok
