Repository ovh-ux/ovh-ui-angular, pull requests merged in 2019-07, with the labels that each got.

#415 build: update yarn.lock file
  yarn.lock
Labels: build

#416 feat(oui-tile): add transclude for term and actions
  packages/oui-tile/README.md
  packages/oui-tile/src/definition/tile-definition.component.js
  packages/oui-tile/src/definition/tile-definition.controller.js
  packages/oui-tile/src/definition/tile-definition.html
  packages/oui-tile/src/index.spec.js
Labels: feature

#419 fix(oui-criteria): fix fields size to medium
  packages/oui-criteria/src/adder/criteria-adder.html
Labels: bug

#417 feat(oui-criteria): add ability to hide operators field
  packages/oui-criteria/README.md
  packages/oui-criteria/src/adder/criteria-adder.html
  packages/oui-criteria/src/adder/criteria-adder.spec.data.json
  packages/oui-criteria/src/adder/criteria-adder.spec.js
Labels: feature

#418 Feat/datagrid
  packages/oui-criteria/src/criteria.controller.js
  packages/oui-criteria/src/index.spec.js
  packages/oui-datagrid/README.md
  packages/oui-datagrid/src/datagrid.controller.js
  packages/oui-datagrid/src/datagrid.directive.js
Labels: enhancement
