Repository ovh-ux/ovh-ui-angular, pull requests merged in 2019-03, with the labels that each got.

#365 feat(oui-popover): add scope attribute for template
  packages/oui-popover/README.md
  packages/oui-popover/src/index.spec.js
  packages/oui-popover/src/popover.controller.js
  packages/oui-popover/src/popover.directive.js
Labels: feature

#368 feat(oui-slideshow): add on click event for navigation
  packages/oui-slideshow/README.md
  packages/oui-slideshow/src/index.spec.js
  packages/oui-slideshow/src/slideshow.component.js
  packages/oui-slideshow/src/slideshow.controller.js
Labels: enhancement

#367 Feat/onclick header tab
  packages/oui-header-tabs/README.md
  packages/oui-header-tabs/src/header-tabs-item.component.js
  packages/oui-header-tabs/src/header-tabs-item.html
  packages/oui-header-tabs/src/index.spec.js
Labels: enhancement

#376 fix(oui-tabs): add button type
  packages/oui-tabs/src/item/tabs-item.html
Labels: bug
