Repository ovh-ux/ovh-ui-angular, pull requests merged in 2019-05, with the labels that each got.

#397 fix(oui-clipboard): set button type
  packages/oui-clipboard/src/clipboard.html
Labels: bug

#398 feat(oui-tabs): allow to select active tab item
  packages/oui-tabs/README.md
  packages/oui-tabs/src/index.spec.js
  packages/oui-tabs/src/item/tabs-item.controller.js
  packages/oui-tabs/src/tabs.component.js
  packages/oui-tabs/src/tabs.controller.js
  packages/oui-tabs/src/tabs.html
Labels: enhancement, feature

#396 feat(oui-navbar): allow to have custom content in menu header
  packages/oui-navbar/README.md
  packages/oui-navbar/src/index.spec.js
  packages/oui-navbar/src/menu/navbar-menu.component.js
  packages/oui-navbar/src/menu/navbar-menu.controller.js
  packages/oui-navbar/src/menu/navbar-menu.html
  packages/oui-navbar/src/navbar.html
  packages/oui-navbar/src/toggler/navbar-toggler.component.js
  packages/oui-navbar/src/toggler/navbar-toggler.html
Labels: enhancement, feature

#401 fix(oui-tabs): select dynamically active tab
  packages/oui-tabs/src/tabs.controller.js
Labels: bug

#404 feat: allow to pass placement to oui-action-menu
  packages/oui-action-menu/README.md
  packages/oui-dropdown/README.md
  packages/oui-dropdown/src/dropdown.controller.js
  packages/oui-dropdown/src/index.spec.js
Labels: feature
