Repository ovh-ux/ovh-ui-angular, pull requests merged in 2020-01, with the labels that each got.

#449 fix(oui-dropdown): afterClose should remove the focus
  packages/oui-dropdown/src/trigger/dropdown-trigger.controller.js
Labels: bug

#450 Fix/popover tests
  packages/oui-field/src/field.controller.js
  packages/oui-field/src/field.html
  packages/oui-field/src/index.spec.js
  packages/oui-popover/README.md
  packages/oui-popover/src/popover.controller.js
  packages/oui-popover/src/popover.directive.js
  packages/oui-tile/src/index.spec.js
Labels: bug, feature

#451 fix(oui-calendar): dynamic changes for min and max date
  packages/oui-calendar/README.md
  packages/oui-calendar/src/calendar.controller.js
Labels: enhancement

#454 feat(oui-radio-toggle-group): add column direction
  packages/oui-radio/README.md
  packages/oui-radio/src/toggle-group/radio-toggle-group.component.js
Labels: feature

#452 fix(oui-collapsible): add helper to remove html on heading
  packages/common/component-utils.js
  packages/oui-collapsible/src/collapsible.controller.js
  packages/oui-collapsible/src/collapsible.html
Labels: enhancement
